// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	walker "github.com/icecream78/node_shrinker/walker"
	mock "github.com/stretchr/testify/mock"
)

// Walker is an autogenerated mock type for the Walker type
type Walker struct {
	mock.Mock
}

// Walk provides a mock function with given fields: path, callback, errCallback
func (_m *Walker) Walk(path string, callback walker.WalkFunc, errCallback walker.WalkErrFunc) error {
	ret := _m.Called(path, callback, errCallback)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, walker.WalkFunc, walker.WalkErrFunc) error); ok {
		r0 = rf(path, callback, errCallback)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
