// Code generated by mockery v1.0.0. DO NOT EDIT.

package shrunk

import mock "github.com/stretchr/testify/mock"

// MockOsI is an autogenerated mock type for the OsI type
type MockOsI struct {
	mock.Mock
}

// Exit provides a mock function with given fields: exitCode
func (_m *MockOsI) Exit(exitCode int) {
	_m.Called(exitCode)
}

// Getwd provides a mock function with given fields:
func (_m *MockOsI) Getwd() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: filepath
func (_m *MockOsI) Remove(filepath string) error {
	ret := _m.Called(filepath)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(filepath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveAll provides a mock function with given fields: filepath
func (_m *MockOsI) RemoveAll(filepath string) error {
	ret := _m.Called(filepath)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(filepath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stat provides a mock function with given fields: filepath
func (_m *MockOsI) Stat(filepath string) (*FileStat, error) {
	ret := _m.Called(filepath)

	var r0 *FileStat
	if rf, ok := ret.Get(0).(func(string) *FileStat); ok {
		r0 = rf(filepath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*FileStat)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(filepath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
